const places: LocationType[] = [
	{
		images: ["/assets/images/img1.jpg", "/assets/images/img11.jpg"],
		title: "Apartment in Lagos",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "amazing views",
	},

	{
		images: ["/assets/images/img2.webp", "/assets/images/img12.webp"],
		title: "5 BR detached",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "beach",
	},
	{
		images: ["/assets/images/img3.webp", "/assets/images/img13.webp"],
		title: "3 BR duplex",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "tropical",
	},
	{
		images: ["/assets/images/img4.webp", "/assets/images/img14.jpg"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "islands",
	},
	{
		images: ["/assets/images/img5.jpeg", "/assets/images/img15.jpg"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "amazing pools",
	},
	{
		images: ["/assets/images/img6.webp", "/assets/images/img16.jpg"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "shared homes",
	},
	{
		images: ["/assets/images/img7.jpg", "/assets/images/img17.jpg"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "arctic",
	},
	{
		images: ["/assets/images/img8.webp", "/assets/images/img18.webp"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "design",
	},
	{
		images: ["/assets/images/img9.webp", "/assets/images/img19.webp"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "surfing",
	},
	{
		images: ["/assets/images/img10.webp", "/assets/images/img20.webp"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "national parks",
	},
	{
		images: ["/assets/images/img11.jpg", "/assets/images/img1.jpg"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "beds and breakfast",
	},
	{
		images: ["/assets/images/img12.webp", "/assets/images/img2.webp"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "caves",
	},
	{
		images: ["/assets/images/img13.webp", "/assets/images/img3.webp"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "country side",
	},
	{
		images: ["/assets/images/img14.jpg", "/assets/images/img4.webp"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "lake",
	},
	{
		images: ["/assets/images/img15.jpeg", "/assets/images/img5.jpeg"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "luxe",
	},
	{
		images: ["/assets/images/img16.jpg", "/assets/images/img6.webp"],
		title: "Comfy condo in Lekki",
		host: "Ayo Abimbola",
		availableDate: "Jan 5 - 10",
		cost: 50,
		isLiked: false,
		id: Math.random(),
		rating: "5.0",
		category: "tiny homes",
	},
];

const categories: FilterItem[] = [
	{
		imgPath: "/assets/filter-icons/omg.jpeg",
		title: "OMG!",
	},
	{
		imgPath: "/assets/filter-icons/bch.jpeg",
		title: "beach",
	},
	{
		imgPath: "/assets/filter-icons/amz-pools.jpeg",
		title: "amazing pools",
	},
	{
		imgPath: "/assets/filter-icons/tropical.jpeg",
		title: "tropical",
	},
	{
		imgPath: "/assets/filter-icons/shomes.jpeg",
		title: "shared homes",
	},
	{
		imgPath: "/assets/filter-icons/islands.jpeg",
		title: "islands",
	},
	{
		imgPath: "/assets/filter-icons/arctic.jpeg",
		title: "arctic",
	},
	{
		imgPath: "/assets/filter-icons/amz-views.jpg",
		title: "amazing views",
	},
	{
		imgPath: "/assets/filter-icons/design.jpg",
		title: "design",
	},
	{
		imgPath: "/assets/filter-icons/surfing.jpg",
		title: "surfing",
	},

	{
		imgPath: "/assets/filter-icons/bedab.jpg",
		title: "beds and breakfast",
	},
	{
		imgPath: "/assets/filter-icons/nat-parks.jpg",
		title: "national parks",
	},
	{
		imgPath: "/assets/filter-icons/caves.jpg",
		title: "caves",
	},
	{
		imgPath: "/assets/filter-icons/count-side.jpg",
		title: "country side",
	},
	{
		imgPath: "/assets/filter-icons/lake.jpg",
		title: "lake",
	},
	{
		imgPath: "/assets/filter-icons/luxe.jpg",
		title: "luxe",
	},
	{
		imgPath: "/assets/filter-icons/tny-homes.jpg",
		title: "tiny homes",
	},
	{
		imgPath: "/assets/filter-icons/campers.jpg",
		title: "campers",
	},
	{
		imgPath: "/assets/filter-icons/castles.jpg",
		title: "castles",
	},
	{
		imgPath: "/assets/filter-icons/aframes.jpg",
		title: "a-frames",
	},
	{
		imgPath: "/assets/filter-icons/golfing.jpg",
		title: "golfing",
	},
	{
		imgPath: "/assets/filter-icons/mansions.jpg",
		title: "mansions",
	},
	{
		imgPath: "/assets/filter-icons/cabins.jpg",
		title: "cabins",
	},
];

export { places, categories };
